### ISSUE TITLE
Add remote relay chain support via RPC

### ISSUE THREAD

**Issue by Curu24** [zeitgeistpm/zeitgeist#1010]
Recent release is not supporting the `--relay-chain-rpc-url` flag. When added it gets ignored and continues with the integrated relay chain. This feature got introduced in 0.9.32 so probably updating dependencies to 0.9.32 and above should fix this https://github.com/paritytech/cumulus/pull/1585

**Comment by sea212** [comment]
Closed by https://github.com/zeitgeistpm/zeitgeist/pull/966.

**Comment by sea212** [comment]
Reopening because support was only partially implemented.
