### ISSUE TITLE
Release event with only changed fields when market is edited

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/zeitgeist#1019]
It would be good to have event `PredictionMarkets.MarketEdited` which only has fields whose data got updated by the user. This should allow lay person to identify the changed data and reduce work for downstreams especially. 

Presently subsquid would check every field on the market schema before and after edit to track changes.

Example: As seen for `marketId:535` on testnet, its difficult to make out what changed post edit.

<img width="288" alt="Screenshot 2023-06-10 at 1 11 34 PM" src="https://github.com/zeitgeistpm/zeitgeist/assets/36529278/54a63ba3-f395-4e88-8c86-e337c052be64">
<img width="288" alt="Screenshot 2023-06-10 at 1 11 26 PM" src="https://github.com/zeitgeistpm/zeitgeist/assets/36529278/b1d50b53-3018-454c-99d5-8996c0b8bd23">

**Comment by sea212** [comment]
The solution should be on the Squid side imo, as the actual metadata lives in IPFS it should fetch the data and diff it. We could also enforce providing the actual metadata as a bytearray to the on-chain call and checking if it matches the metadata, but that introduces unnecessary load on the chain and raises the transaction cost, as the transaction gets bigger and computation time increases.

**Comment by maltekliemann** [comment]
Closing because we're removing market editing completely.
