### ISSUE TITLE
Free avatar minting for Seers in Discord

### ISSUE THREAD

**Issue by Boibit** [zeitgeistpm/zeitgeist#1020]
Enable Seers to mint base Zeitgeist avatars without burning 200ztg.

**Comment by sea212** [comment]
I think all solutions are viable that @yornaath mentioned, but the one where the chain queries Discord is the most complex one and the effort is not worth the value.
We can't make the transaction entirely free, as fees have to be paid as part of a DOS protection. We can remove the burn amount though. What is the idea behind having a burn amount anyways?
The idea with the bot is the easiest to maintain and requires the least chain resources. On the other hand it does not scale well, as the bot has to pay the TX fees for every mint.
I am leaving it up to you guys to choose one options, either adding a maintainer account that maintains the seer account list or having a privileged account that can mint for free for other accounts. Another option would be to remove the burn at all.

**Comment by maltekliemann** [comment]
Closed as outdated.
