### ISSUE TITLE
Market creator or oracle should be allowed to change the market description

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#1077]
For the sake of clarification, one of these should be allowed to change the market description. The old descriptions should not be overwritten to make it easier to follow the changes made and potentially use an older version to resolve the market. Should probably ask for a bond to make it impossible to spam. The change should consist of a new description and a summary/justification of the changes (following the system stackexchange uses).

This can help MCs/oracles to clarify how the market is going to resolve. For example, the market https://app.zeitgeist.pm/markets/159 could be changed by adding another resolution criterion: 

> If the debt limit is suspended, the market resolves to "No."

Here's an example where things might go too far: https://app.zeitgeist.pm/markets/211. This was supposed to be a market specifically about the Blackrock ETF. But the way it is phrased, it will trivially resolve to "Yes" because there are many Bitcoin ETFs out there already. The MC/oracle could change the title/description here to "Will the Blackrock ETF be Approved Before the End of 2023?". The summary/justification would explain that the previous version of the market was phrased incorrectly. But this sucks for the people who already bet "Yes".

Market creator feels more natural but I'm mentioning the oracle here because it is in charge of resolving the market, so clarifying _how_ it is going to resolve the market seem

**Comment by Robiquet** [comment]
Anything that alters the original resolution criteria shouldn't be allowed as traders would have already positioned themselves based off that description. I think additions to resolution criteria where things are ambiguous are ok though. Given this, I'm not sure if edits are the right approach. Maybe additional metadata can be added instead, though I think it would need to be reviewed

**Comment by lsaether** [comment]
Metadata is flexible and can handle arbitrary URIs. Market creators can choose a URI when they deploy a market. We can accomplish this feature set by linking the metadata to a page that can be edited. The front-end will need to handle a new "standard" for the metadata though. And it's the onus of the market creator / market maintainer if they want to keep a history of all the changes they make in the metadata. We should display a message on the front-end when an editable metadata is detected so the user knows that the information related to the market can change.

**Comment by maltekliemann** [comment]
Adding additional metadata seems like the way to go.
