### ISSUE TITLE
Fees incurred in ForeignAsset:0/ForeignAsset:2 don't go to treasury

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/zeitgeist#1091]
On testnet, fees incurred in `ForeignAsset: 0`/`ForeignAsset: 2` don't go to treasury account (i.e, they are just deducted from the source).

Why is that only `ForeignAsset: 1` gets collected by treasury? This should help in configuring `AssetTxFeePaidEvent` on Subsquid.

Ref:
1. `dDywmamjrDkaT18ybCRJBfax65CoxJNSWGZfwiQrbkAe95wq3` paid `3520398` `ForeignAsset: 0`
Follow: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/4093090
2. `dE3pPiRvdKqPD5bUDBu3Xpi83McE3Zf3UG8CbhWBQfvUywd7U` paid `244974359` `ForeignAsset: 2`
Follow: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/4135737

**Comment by Chralt98** [comment]
Can you provide evidence that `ForeignAsset: 1` transfers the fees to the treasury?

**Comment by Chralt98** [comment]
I tend to believe at the moment that the ForeignAsset 0 and 2 just drop below the existential deposit again and again.

https://github.com/paritytech/polkadot-sdk/blob/cdbdbc7546b34907a0c5843699d4287179b692fe/substrate/frame/support/src/traits/tokens/fungible/regular.rs#L212

Can you send the minimum amount of `500,000,000` for foreign asset 2 and `10,000,000` for foreign asset 0 to the treasury account for the different foreign assets?

**Comment by saboonikhil** [comment]
> Can you provide evidence that `ForeignAsset: 1` transfers the fees to the treasury?

1. `dE3pPiRvdKqPD5bUDBu3Xpi83McE3Zf3UG8CbhWBQfvUywd7U` paid `244974359` `ForeignAsset: 1`
Follow: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/4135703
2. `dE3pPiRvdKqPD5bUDBu3Xpi83McE3Zf3UG8CbhWBQfvUywd7U` paid `244974359` `ForeignAsset: 1`
Follow: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/4135646

**Comment by Chralt98** [comment]
Foreign asset 0 fee works now [here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/4287409).

Foreign asset 2 fee works now [here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/4287418).

Treasury received the fees! The fix was to fund the existential deposit to the treasury for asset 0 and asset 2.
