### ISSUE TITLE
[PredictionMarkets] Can't sell complete sets on inactive market

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#1093]
That's definitely wrong. Why would this not be allowed? Sucks for LPs who are needlessly sitting on their complete sets until the market resolves.

**Comment by sea212** [comment]
Selling complete sets would change the probability, although the prediction / trade period is over, right? Seems not intuitive to me. Would be fine to allow selling complete sets in this case if we figure out a way to freeze prediction outcomes.

**Comment by maltekliemann** [comment]
> Selling complete sets would change the probability, although the prediction / trade period is over, right?

No, that's completely independent.
