### ISSUE TITLE
[orderbook-v1] Use `NamedMultiReservableCurrency` instead of `ZeitgeistAssetManager`

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#1114]
Did the same thing in neo-swaps. It's cleaner.

**Comment by Chralt98** [comment]
https://github.com/zeitgeistpm/zeitgeist/blob/4e2569526fa1a8d4b9c04f7aaecc380ef8b7f09d/zrml/orderbook-v1/src/lib.rs#L62

Do you mean this? It's already on main o.O
