### ISSUE TITLE
CI doesn't catch errors caused by comitting review suggestions

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#1128]
The error https://github.com/zeitgeistpm/zeitgeist/actions/runs/6336670360/job/17210205112 on `main` was caused by comitting this review suggestion: https://github.com/zeitgeistpm/zeitgeist/pull/1100#discussion_r1338409380.

Apparently the CI of the PR failed as well, but I was still able to merge the PR.

**Comment by sea212** [comment]
I think the current node team should maintain the capability to merge PRs with failing pipeline, in case something like the taplo issue happens which should not really block the workflow until resolved.

Anyways, I think reinforcing having to run the pipeline after commits makes sense. I think one solution could be to instruct Mergify to reset the label to `s:in-progress` once a commit was pushed.
Besides that, Mergify will also merge PRs if the CI passes completely.
