### ISSUE TITLE
Bondless market creation

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/zeitgeist#1175]
Users currently have to pay two bonds when creating a market, the creation bond and the oracle bond. I propose that we make it possible to remove the need for bonds during market creation in order to reduce friction for our users.

**Creation bond**
We currently use with to prevent spam/inappropriate markets, though we have transaction fees to prevent this to an extent. I think most of the moderation should be moved off chain where we already have some tooling to support this. We can build more such as simple moderation interface to remove markets from the app and IPFS in one click.

**Oracle bond**
Polymarket users only pay this bond when the user has to report a market. I think a similar mechanism can work for us as there will always to a user incentivised to do so.

**Comment by maltekliemann** [comment]
Closing for now as this is part of upcoming protocol simplifications.
