### ISSUE TITLE
Properly configure pallet-assets `RemoveItemsLimit`

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#1176]
Currently the pallet-assets instances in the runtime use a conservative `RemoveItemsLimit` configuration. Optimally configuring `RemoveItemsLimit` requires that weights for pallet-assets from the reference machine are available. Once those are available, all pallet-assets instances should use an optimized value for `RemoveItemsLimit`.

**Comment by maltekliemann** [comment]
Closing as no longer relevant.
