### ISSUE TITLE
Add pallet-xcm benchmark and weights

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist#1230]
https://github.com/zeitgeistpm/zeitgeist/blob/a5f4b397ba09a95bb2037255dbec99ac6844e4e1/runtime/common/src/lib.rs#L533

We just use the standard test weights for xcm functions. We might want to benchmark our own weights for our reference machine.

**Comment by sea212** [comment]
Duplicate of https://github.com/zeitgeistpm/zeitgeist/issues/1082
