### ISSUE TITLE
Genesis storage root hash differs

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#131]
The most recent source code will compile into a binary that creates a different storage root hash in genesis, although the same chainspec is applied.

**Comment by c410-f3r** [comment]
With the upcoming integration of new runtime pallets and initial configurations (staking, crowdloan, Liquidity mining, ...), I am afraid more genesis conflicts will appear because most of them do modify initial state.

**Comment by lsaether** [comment]
Closed in #146
