### ISSUE TITLE
Issue in testnet multiplying tokens easy

### ISSUE THREAD

**Issue by ojofirme** [zeitgeistpm/zeitgeist#137]
So I am newbie and have none tec abilities at all.

Today at the crowcast Logan said there was a possibility of arbitrage. 

So I went to the website 

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbp-rpc.zeitgeist.pm#/extrinsics

Sold my tokens but was weired that I was not able to choose if karura or shiden etc..

then able to sell for arbitrage.

The issue is that I sell my tokens for each horse the same amount. therefore I was ablle to sell in the 9 slots not only in the arbitrage one but in the nine of them started with slot 1 but had tried with the 3 slots already

**Comment by lsaether** [comment]
system is working as expected

good job

**Comment by ojofirme** [comment]
So that means that everything is ok, may i keep doing it¿? or is it going to get fixed?
