### ISSUE TITLE
[LiquidityMining] Fund the reward pool via inflation

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/zeitgeist#175]
The LiquidityMining pallet uses a pot of funds to reward liquidity providers who have provided liquidity to pools. Currently, the pot of funds which get distributed to LPs is funded initially at genesis. This means it would eventually run out of funds. In order to keep this pot of funds funded indefinitely, we should route some of the inflation tokens to the pot of funds.

**Comment by maltekliemann** [comment]
Closing as outdated (pallet scheduled to be removed).
