### ISSUE TITLE
[LiquidityMining] Only selected markets should be rewarded

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/zeitgeist#176]
Currently all the pools on Zeitgeist are rewarded based on the amount of time is remaining for the market. However, I can foresee possible situations where LPs provide liquidity to pools no one cares about simply to gather the rewards without any risk. Instead, we want to be able to use the LM as an additional incentive for specific markets (as determined by governance). 

- LiquidityMining should have a storage item for `IncentivizedMarkets`, which can be adjusted by a root origin, and hold a `vec` of `market_id`s that are being incentivized by LiquidityMarkets.
- The `IncentivizedMarkets` should also allow for weights to be set for each market, so that some markets can be rewarded more than other markets. This would also be configurable by the root origin via governance.

**Comment by maltekliemann** [comment]
Closing as outdated (pallet scheduled to be removed).
