### ISSUE TITLE
[CICD] Add hosted runner

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#185]
Currently GitHub uses the [Standard_DS2_v2](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series) machine to execute workflows on. [hardware resources:](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

>  2-core CPU
    7 GB of RAM memory
    14 GB of SSD disk space

The accuracy of the generated weights during the benchmark workflow on such a machine is not acceptable. A machine with 32 gb of ram, ideally 64 gb of ram, and optimally a relatively modern processor is required. Ideally it is a dedicated (in terms of hardware and software) self hosted machine, but one of the [machines GitHub AE offers](https://docs.github.com/en/github-ae@latest/actions/using-github-hosted-runners/about-ae-hosted-runners#hardware-specifications) is also a valid option.

As for GitHub AE hosted runners, I suggest one of those:

- [Standard_DS13_v2](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series-memory)
- [Standard_D16as_v4](https://docs.microsoft.com/en-us/azure/virtual-machines/dav4-dasv4-series)

The [Standard_DS13_v2](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series-memory) has a weaker processor, but it is possible to get an eight core processor and 56 GB ram. The memory optimized [Standard_DS13_v2](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series-memory) is perfect of in-memory analysis, which is exactly what the benchmarks do: Gather massive amounts of data in memory during the benchmark and analyze it afterwards. It has the perfect cost-to-value ratio for our use-case, but the relatively weak processor leads to longer benchmark workflow times and higher weights, which result in a lower per-block capacity of the Zeitgeist chain.
The [Standard_D16as_v4](https://docs.microsoft.com/en-us/azure/virtual-machines/dav4-dasv4-series) offers a fast 16 core CPU and 64 GB memory. It will run the workflow faster and the resulting weights lead to a higher per-block capacity. The drawback is, that the cost-to-value ratio is lower, since we have to pay for the job time on [per core and per minutes basis](https://docs.github.com/en/github-ae@latest/actions/using-github-hosted-runners/about-ae-hosted-runners#billing). Since the actual benchmarks only run on a single core (this is likely improvable) cost-wise using this machine is inefficient.

**Comment by lsaether** [comment]
@sea212 GitHub AE is still in beta so is currently free right? I didn't see anywhere that said they've decided on pricing yet. If that's the case let's just use the beefier hosted machine, and once we know what the cost is we can re-evaluate if we want to switch to a similarly specced self hosted runner or continue with the GitHub AE one

**Comment by sea212** [comment]
@lsaether I agree, this seems reasonable. We can use the evaluation above again once we have to pay for the runners. I will prepare a message for GH to request a hosted runner.

**Comment by sea212** [comment]
Unfortunately GitHub keeps ignoring our requests. Next task: Setup self-hosted runner.

**Comment by sea212** [comment]
Self-hosted runner configured and registered: **runtime-benchmark**
