### ISSUE TITLE
Use Substrate's `Collective` for the Advisory Committee

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/zeitgeist#205]
The Advisory Committee is elected by the on-chain council and is tasked as the main curatorial body of Zeitgeist (keeping the markets high quality). On the front-end we will display all markets that have been approved by the Advisory Committee as a good market, while the markets that were created using the `Permissionless` flag will be displayed behind a warning. 

After adding the `Collective` pallet to the runtime, the Advisory Committee should be an allowed origin to the `approve_market` and `reject_market` extrinsics in the `PredictionMarkets` pallet.

**Comment by sea212** [comment]
This could be a potential path of solving this issue:

- [ ] Include *pallet_collective* into the runtime
- [ ] Add the collective instance for the Advisory Committee to the `PredictionMarkets` pallet
- [ ] Add the respective origin as an allowed origin to `approve_market` and `reject_market` extrinsics within the `PredictionMarkets` pallet

at this point, the root can call `set_members` to set the members of the Advisory Committee.
Once the court is realized (maybe create a new issue for that):
- [ ] Implement the `ChangeMembers` trait to allow the court to modify the members of the Advisory Committee.

**Comment by zachanon** [comment]
If appropriate I would like to be assigned to this issue.

**Comment by sea212** [comment]
> If appropriate I would like to be assigned to this issue.

Awesome, thank you for tackling this issue zachanon!
Please let us know if something about the task is not 100% clear.
