### ISSUE TITLE
Change Scalar range type from `(u128, u128)` to `RangeInclusive`

### ISSUE THREAD

**Issue by c410-f3r** [zeitgeistpm/zeitgeist#220]
https://github.com/zeitgeistpm/zeitgeist/blob/8e3387c734eb984726e07a369bbb2d54de68ae6f/primitives/src/market.rs#L146-L147

Needs `apps` support and a new migration

**Comment by saboonikhil** [comment]
I think we have to add `RangeInclusive` in typesdefs.json
I am getting error while playing with `outcomeRange` in market schema.

What do you think? @sea212 @c410-f3r

**Comment by sea212** [comment]
@saboonikhil  Yes, that's true. Can you change it in https://github.com/zeitgeistpm/zeitgeist/blob/main/misc/types.json#L89 and in sdk types please?

**Comment by c410-f3r** [comment]
RangeInclusive is a built-in structure of the standard library and should have native `api` support.

https://github.com/polkadot-js/api/pull/3791 added support for ranges types and if some error is occurring, then it is a upstream bug
