### ISSUE TITLE
[Orderbook-v1] Implement fuzz targets

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#243]
Pallet *orderbook-v1* still needs fuzz targets to test its stability. Fuzz testing with *cargo-fuzz* is described in the [Rust Fuzz Book](https://rust-fuzz.github.io/book/cargo-fuzz.html).
The pallets *swaps* and *prediction-markets* already implement one fuzz target to fuzz test them, which can serve as an example.

Implement at least one fuzz target that covers the possible logical paths as good as possible. For example, create a bid on one side and fulfill it at the other side. As a bonus, move the different logical paths into distinguished fuzz targets.

Add the commands to execute the fuzz targets to *scripts/tests/fuzz.sh*, once all targets are implemented.

**Comment by zachanon** [comment]
Hello and happy Saturday, or maybe Samstag. I would like to work on this issue if possible.

**Comment by sea212** [comment]
Solved in #247
