### ISSUE TITLE
[Analytics] Extend fuzz workflow to generate and commit coverage reports

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#264]
[The workflow that contains the job to execute the fuzz tests](https://github.com/zeitgeistpm/zeitgeist/blob/51c79db9f44a6d8491b2b398b911466fa32e58df/.github/workflows/rust.yml) should be extended to [collect test coverage data](https://rust-fuzz.github.io/book/cargo-fuzz/coverage.html#generate-code-coverage-data) during the *fuzz* job. Another step within the *fuzz* job should [create a coverage report](https://doc.rust-lang.org/beta/unstable-book/compiler-flags/instrument-coverage.html#creating-coverage-reports) for the fuzz test coverage data. Another job, that depends on the *fuzz* job, should finally commit the reports into a specific folder within the project.

**Comment by Chralt98** [comment]
https://rust-fuzz.github.io/book/cargo-fuzz/coverage.html

This is the only possible way to get code coverage data for our fuzz tests currently. The problem with this solution is, that it takes too long. I tried it out and the workflow stopped after more than 6 hours without finishing.

<img width="1937" alt="Bildschirmfoto 2022-09-27 um 09 01 10" src="https://user-images.githubusercontent.com/33418719/192457040-5ffcb487-d391-4fa3-8022-e6e70b659f57.png">

[This](https://github.com/zeitgeistpm/zeitgeist/blob/b741e764b4f80a62be347f8de9189aaf29145747/.github/workflows/rust.yml#L107-L146) was my workflow configuration. 

This was my fuzz.sh:

https://github.com/zeitgeistpm/zeitgeist/blob/b741e764b4f80a62be347f8de9189aaf29145747/scripts/tests/fuzz.sh#L35-L92

[This](https://github.com/zeitgeistpm/zeitgeist/actions/runs/3128348500/jobs/5076074481) was the workflow.
