### ISSUE TITLE
Unbalanced addition to liquidity pool when creating a market

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/zeitgeist#268]
As explained in #254 if amount to be added to liquidity pool of each asset is not the same - for example for binary market, if someone wants to deploy pool with 150 "Yes" assets and 110 "No" assets we would need to buy complete set of 150 assets first and after addition to liquidity pool, account will have 40 "No" assets left on balance which he can then exchange to ztg.

There should be possibility to avoid having leftover assets on balance.
Research the implications of such unbalanced addition of liquidity.

**Comment by maltekliemann** [comment]
Closed as no longer relevant.
