### ISSUE TITLE
[Node] Update chain specifications before next testnet

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#286]
Before the next testnet is launched, the chain specification files for the standalone testnet and the parachain testnet should be updated. This should be done as the last step, after all changes to the Zeitgeist node were implemented.

Depends on #282: Only resolve this issue once the only remaining task in #282 is "Checklist for v0.2.0 release #236"

**Comment by lsaether** [comment]
closed in #335
