### ISSUE TITLE
[Court] `JurorsStatus::Tardy` juror will never be changed back to `JurorStatus::Ok`

### ISSUE THREAD

**Issue by c410-f3r** [zeitgeistpm/zeitgeist#291]
Once a juror is marked as `JurorStatus::Tardy`, he will always be tardy and I am not sure if this behaviour is desired.

**Comment by ckamm** [comment]
It looks to me like this causes issues. In a subsequent dispute a tardy juror will neither receive an incentive when voting for the best option, nor will their stake be slashed when voting for something other than the best two options. See `slash_losers_to_award_winners` use of `non_tardy_jurors_with_votes`.

**Comment by c410-f3r** [comment]
Yes, already tardy jurors that voted within the `CourtCaseDuration` duration are valid and should be eligible to receive rewards or be slashed, therefore, `non_tardy_jurors_with_votes`  could be renamed to something like `valid_jurors_with_votes` and also yield valid tardy jurors.

Thanks again for spotting another problem
