### ISSUE TITLE
[Court] jurors can vote, then leave the court to avoid penalties

### ISSUE THREAD

**Issue by ckamm** [zeitgeistpm/zeitgeist#293]
If I read https://github.com/zeitgeistpm/zeitgeist/blob/main/zrml/court/src/lib.rs#L79 right, jurors can leave the court and unreserve their stake at any time.

This likely means that a juror could have their vote counted in a dispute and be eligible for incentives - while avoiding any disincentives.

@c410-f3r

**Comment by c410-f3r** [comment]
Correct, `exit_court` will un-reserve everything including what would be used for potential slashes. A discrete balance could be used in the future to retain court stakes but for now I will create a PR to remove all remaining references of departed jurors.

Thanks for spotting this problem 👍
