### ISSUE TITLE
Rename "zrml" to pallets

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/zeitgeist#34]
ZRML is an archaic name back when Substrate pallets were called runtime modules and there things like the SRML (Substrate Runtime Module Library) and ORML.

Now the ergonomic way to name things is simply "pallet" so we should migrate all zrml -> pallet namespaces.

**Comment by lsaether** [comment]
Let's just keep zrml

**Comment by sea212** [comment]
Yeah, and claim that  "zrml" means "zeitgeist runtime module libraries" :smile:
