### ISSUE TITLE
Include missing types in types.json

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/zeitgeist#368]
There's some issue while fetching the block details (reading events) from `#77113`

Can be viewed here - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/0x0fbcdc8bc430f6911b254f6e5aa559e5bbad685755500dd98932e1de16d5a9a1

One of the possible solutions is updating all the types alerted below by the chain metadata.
`Unknown types found, no types for Collator2, Juror, Nominator2, OwnedValuesParams, Rikiddo`

**Comment by lsaether** [comment]
Reducing this to high priority
