### ISSUE TITLE
Add or modify event params

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/zeitgeist#396]
Modify param `Currency` to `CurrencyId` (to resolve type conflicts) for the following `currency` events: 
1. Transferred
2. Deposited
3. Withdrawn

_(Note: Deferring the above point to continue with the manual workaround since this would require making changes in the currency pallet)_

Add modified market fields along with `MarketIdOf` (to ensure that the logic remains at one place) for the following `predictionMarkets` events:
1. MarketApproved
2. MarketStartedWithSubsidy
3. MarketInsufficientSubsidy
4. MarketReported
5. MarketDisputed
6. MarketRejected
7. MarketCancelled

**Comment by sea212** [comment]
Extra todo: State changes that aren't logged?
