### ISSUE TITLE
[Squid] Add amount as event param in BoughtCompleteSet/SoldCompleteSet

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/zeitgeist#443]
This will help in tracking the units of outcome assets being transferred.

The extrinsic has this value but it becomes untraceable (for the _subsquid-processor_) when the extrinsic is part of the utility batch calls.

**Comment by saboonikhil** [comment]
I have a query related to this issue:

Does the transfer happen between pool and user accounts? For example, when the user buys some units of a market - are the outcome assets transferred from the pool account to the user account?

**Comment by sea212** [comment]
`buy_complete_set` will generate/mint tokens, whereas `sell_complete_set` will burn tokens.
Currently no event is emitted, but once Zeitgeist v0.2.4 runtime is used, the balances pallet will emit a `Deposit` or `Withdraw` event whenever tokens are minted or burned, for example when a set was bought or when some transaction fees were burned.
