### ISSUE TITLE
[Squid] Record changes to Pool

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/zeitgeist#466]
Before fully moving the pool details to app, I wanted to ensure that all changes to the Pool are being well covered by some event.

A quick scan on https://github.com/zeitgeistpm/zeitgeist/blob/main/zrml/swaps/src/lib.rs has revealed the following:
1. PoolStatus transits from `CollectingSubsidy` to `Active` with emission of event `MarketStartedWithSubsidy`
2. PoolStatus transits from `Active` to `Stale` with extrinsic `adminSetPoolAsStale`
3. TotalSubsidy changes with emission of events `PoolJoinSubsidy`, `SubsidyCollected`, `PoolExitSubsidy`

It would be great to have these changes (also any other) as an event parameter for ease in tracking via subsquid.

**Comment by maltekliemann** [comment]
1. and 3. only relate to Rikiddo pools and will be done at a later time.
