### ISSUE TITLE
[Squid] Review balances.transferKeepAlive

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/zeitgeist#476]
This is for older data which doesn't have exclusive `balances.Withdraw` event associated for the txn fees.

I noticed that for the account `dDz7L2zdPVCJG3aEprm1XjMdRUyb8QWckB5nWcnrz7eCV6JEc`: the balance remained intact after execution of the extrinsic `balances.transferKeepAlive` at [#187](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/187) (it looks like the acc was transferring units to itself).

The balance is `7.9980 kZBS` when queried at block `#186` and `#188` respectively. Is this the desired result?

**Comment by maltekliemann** [comment]
That's an unfortunate rounding error. If you run this...

```js
const hash_186 = await api.rpc.chain.getBlockHash(186);
const api_186 = await api.at(hash_186);
let balance_186 = await api_186.query.system.account(
  "dDz7L2zdPVCJG3aEprm1XjMdRUyb8QWckB5nWcnrz7eCV6JEc"
);
console.log(balance_186.data.free.toNumber());

const hash_188 = await api.rpc.chain.getBlockHash(188);
const api_188 = await api.at(hash_188);
let balance_188 = await api_188.query.system.account(
  "dDz7L2zdPVCJG3aEprm1XjMdRUyb8QWckB5nWcnrz7eCV6JEc"
);
console.log(balance_188.data.free.toNumber());
```

... then you get:

```shell
79980291669231
79980020669231
```

**Comment by saboonikhil** [comment]
Transaction fees based on the calculation at [subsquid](https://github.com/zeitgeistpm/zeitgeist-subsquid/blob/main/src/processor/balances.ts#L887-L902) should be `271000000` which would have brought the net balance to `79979729000000` - I was expecting `7.9979 kZBS`.

**Comment by saboonikhil** [comment]
Thank you @maltekliemann, looks like I need to start tracking `parachainStaking.Rewarded` which records balance addition to `dDz7L2zdPVCJG3aEprm1XjMdRUyb8QWckB5nWcnrz7eCV6JEc` every 10th block i.e, 170, 180, 190.

The transaction fees `271000000` (79980291669231 - 79980020669231) for the above extrinsic seem to be fair.
