### ISSUE TITLE
[swaps] Withdrawing liquidity completely is impossible

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#479]
Due to the `Max*Ratio` limits, only a portion of a liquidity pool's total liquidity can be withdrawn (say, 50%). If a pool has only a single provider, that means that this provider can only withdraw 50% of their liquidity with one extrinsic. Then on the next extrinsic, they can withdraw another 25%. And so on...

If multiple people provide liquidity, this is unlikely to be a problem. If we have two providers, each providing 50% of the liquidity, one of them could withdraw their entire liquidity in one go.

**Note.** It is not possible to remove all liquidity from the pool for "mathematical" reasons. As soon as one of the balances goes to zero, you'll get zero division in the price functions. So removing all liquidity from a pool essentially means killing the pool.

**Comment by sea212** [comment]
Restricting the functionality is not an option in my opinion. Two possible paths we talked about are:

1. Use mathematical solutions that don't imply does limitations
2. Implement logic that handles automatic re-execution of the limited math functions until a specific threshold or hard iteration limit.

We can allocate 2 weeks to find a mathematical alternative, should it not work we'll have to go with 2. for now (or another suggestion that was not mentioned yet).
