### ISSUE TITLE
[PM] Figure out what to do with balances when market is destroyed

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#486]
One committee will be able to destroy markets soon. In a future iteration, the following questions have to be tackled:

- What does happen with the bond in case of a permissionless market? In a general case and in the case when the market is of very low quality or even dangerous.
- What does happen with provided liquidity?
- What does happen with the market funding?

**Comment by maltekliemann** [comment]
Currently, `admin_destroy_market` does the following:

- Destroy all balances of outcome tokens
- Does not unreserve any bonds (this has been raised in zeitgeistpm/runtime-audit-1#43)
- Leaves the pool as it is (in particular, doesn't set the pool to stale, etc.)
