### ISSUE TITLE
Invalid Transaction:Custom error: 2

### ISSUE THREAD

**Issue by Wangmmx** [zeitgeistpm/zeitgeist#505]
Hello, I tried to transfer ZTG and got an error "Invalid Transaction:Custom error: 2", can I transfer now or wait for the Mainnet Upgrade?

**Comment by sea212** [comment]
We will unlock transferability during the Token Transferability Event (TTE), which should happen in the coming weeks. Most likely release v0.3.1 will contain the unlocked functionality.
You can be informed by this through [Discord](https://discord.gg/xv8HuA4s8v), [Telegram](https://t.me/zeitgeist_official) and [Twitter](https://twitter.com/ZeitgeistPM)
