### ISSUE TITLE
std::panicking::rust_panic_with_hook

### ISSUE THREAD

**Issue by MaxFoton** [zeitgeistpm/zeitgeist#533]
апр 03 01:16:00 Server systemd[1]: Started Zeitgeist node.
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 Zeitgeist Node
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 ✌️  version 0.2.4-70705a0-x86_64-linux-gnu
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 ❤️  by Zeitgeist PM <contact@zeitgeist.pm>, 2021-2022
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 📋 Chain specification: Battery Station
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 🏷 Node name: maxfoton
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 👤 Role: FULL
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 💾 Database: RocksDb at /services/zeitgeist/battery_station/chains/battery_station_mainnet/db/full
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 ⛓  Native runtime: zeitgeist-33 (zeitgeist-1.tx10.au1)
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 Parachain id: Id(2050)
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 Parachain Account: 5Ec4AhNmfNzKymhQFb5x4LdvawDKJVAs9NGH4yHnQHd5U6Af
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 Parachain genesis state: 0x00000000000000000000000000000000000000000000000000000000000000000090fd12d67b71019c34896d99b145f917c4ff95d58dab4febf5163bf94366420f03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 [Relaychain] 🏷 Local node identity is: 12D3KooWHs8G6U5tmeRFau1GZ42yVQ9LPHfd3CJjj7m4SjXF47a2
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 [Relaychain] 📦 Highest known block at #1468071
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 [Relaychain] 〽️ Prometheus exporter started at 127.0.0.1:9616
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 [Relaychain] Listening for new connections on 127.0.0.1:9945.
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 [🌔 Zeitgeist Parachain] 🏷 Local node identity is: 12D3KooWKFEbGycMSSmZ8mi8374zvV3t8sk1sjesNMofnEbxirdT
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 [🌔 Zeitgeist Parachain] 📦 Highest known block at #949498
апр 03 01:16:00 Server zeitgeist[650495]: 2022-04-03 01:16:00 [🌔 Zeitgeist Parachain] Listening for new connections on 0.0.0.0:9947.
апр 03 01:16:03 Server zeitgeist[650495]: 2022-04-03 01:16:03 [🌔 Zeitgeist Parachain] 🔍 Discovered new external address for our node: /ip4/46.138.245.164/tcp/30337/ws/p2p/12D3KooWKFEbGycMSSmZ8mi8374zvV3t8sk1sjesNMofnEbxirdT
апр 03 01:16:05 Server zeitgeist[650495]: 2022-04-03 01:16:05 [Relaychain] 💤 Idle (0 peers), best: #1468071 (0x0797…e912), finalized #1468068 (0xdea9…ebf1), ⬇ 0 ⬆ 12 B/s
апр 03 01:16:05 Server zeitgeist[650495]: 2022-04-03 01:16:05 [🌔 Zeitgeist Parachain] 💤 Idle (16 peers), best: #949498 (0x6417…3bba), finalized #949498 (0x6417…3bba), ⬇ 15.0kiB/s ⬆ 83.8kiB/s
апр 03 01:16:10 Server zeitgeist[650495]: 2022-04-03 01:16:10 [Relaychain] 💤 Idle (0 peers), best: #1468071 (0x0797…e912), finalized #1468068 (0xdea9…ebf1), ⬇ 0 ⬆ 0
апр 03 01:16:10 Server zeitgeist[650495]: 2022-04-03 01:16:10 [🌔 Zeitgeist Parachain] ⚙️  Syncing  0.0 bps, target=#958106 (30 peers), best: #949498 (0x6417…3bba), finalized #949498 (0x6417…3bba), ⬇ 120.0kiB/s ⬆ 552.7kiB/s
апр 03 01:16:12 Server zeitgeist[650495]: ====================
апр 03 01:16:12 Server zeitgeist[650495]: Version: 0.2.4-70705a0-x86_64-linux-gnu
апр 03 01:16:12 Server zeitgeist[650495]:    0: sp_panic_handler::set::{{closure}}
апр 03 01:16:12 Server zeitgeist[650495]:    1: std::panicking::rust_panic_with_hook
апр 03 01:16:12 Server zeitgeist[650495]:              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/std/src/panicking.rs:610:17
апр 03 01:16:12 Server zeitgeist[650495]:    2: std::panicking::begin_panic_handler::{{closure}}
апр 03 01:16:12 Server zeitgeist[650495]:              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/std/src/panicking.rs:502:13
апр 03 01:16:12 Server zeitgeist[650495]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
апр 03 01:16:12 Server zeitgeist[650495]:              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/std/src/sys_common/backtrace.rs:139:18
апр 03 01:16:12 Server zeitgeist[650495]:    4: rust_begin_unwind
апр 03 01:16:12 Server zeitgeist[650495]:              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/std/src/panicking.rs:498:5
апр 03 01:16:12 Server zeitgeist[650495]:    5: core::panicking::panic_fmt
апр 03 01:16:12 Server zeitgeist[650495]:              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/core/src/panicking.rs:107:14
апр 03 01:16:12 Server zeitgeist[650495]:    6: core::panicking::panic_display
апр 03 01:16:12 Server zeitgeist[650495]:              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/core/src/panicking.rs:63:5
апр 03 01:16:12 Server zeitgeist[650495]:    7: core::option::expect_failed
апр 03 01:16:12 Server zeitgeist[650495]:              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/core/src/option.rs:1663:5
апр 03 01:16:12 Server zeitgeist[650495]:    8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
апр 03 01:16:12 Server zeitgeist[650495]:    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
апр 03 01:16:12 Server zeitgeist[650495]:   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
апр 03 01:16:12 Server zeitgeist[650495]:   11: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
апр 03 01:16:12 Server zeitgeist[650495]:   12: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
апр 03 01:16:12 Server zeitgeist[650495]:   13: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
апр 03 01:16:12 Server zeitgeist[650495]:   14: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
апр 03 01:16:12 Server zeitgeist[650495]:   15: tokio::park::thread::CachedParkThread::block_on
апр 03 01:16:12 Server zeitgeist[650495]:   16: tokio::runtime::handle::Handle::block_on
апр 03 01:16:12 Server zeitgeist[650495]:   17: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
апр 03 01:16:12 Server zeitgeist[650495]:   18: tokio::runtime::task::harness::Harness<T,S>::poll
апр 03 01:16:12 Server zeitgeist[650495]:   19: tokio::runtime::blocking::pool::Inner::run
апр 03 01:16:12 Server zeitgeist[650495]:   20: std::sys_common::backtrace::__rust_begin_short_backtrace
апр 03 01:16:12 Server zeitgeist[650495]:   21: core::ops::function::FnOnce::call_once{{vtable.shim}}
апр 03 01:16:12 Server zeitgeist[650495]:   22: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
апр 03 01:16:12 Server zeitgeist[650495]:              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/alloc/src/boxed.rs:1811:9
апр 03 01:16:12 Server zeitgeist[650495]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
апр 03 01:16:12 Server zeitgeist[650495]:              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/alloc/src/boxed.rs:1811:9
апр 03 01:16:12 Server zeitgeist[650495]:       std::sys::unix::thread::Thread::new::thread_start
апр 03 01:16:12 Server zeitgeist[650495]:              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/std/src/sys/unix/thread.rs:108:17
апр 03 01:16:12 Server zeitgeist[650495]:   23: start_thread
апр 03 01:16:12 Server zeitgeist[650495]:              at ./nptl/./nptl/pthread_create.c:435:8
апр 03 01:16:12 Server zeitgeist[650495]:   24: __GI___clone
апр 03 01:16:12 Server zeitgeist[650495]:              at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:100
апр 03 01:16:12 Server zeitgeist[650495]: Thread 'tokio-runtime-worker' panicked at 'A single consensus digest should be added by the runtime when executing the author inherent.', /home/zeitgeist/.cargo/git/checkouts/nimbus-4590fa7f32e5c755/c5ad2f2/nimbus-consensus/src/import_queue.rs:91

**Comment by sea212** [comment]
Thanks for the report. The bug is resolved, please [upgrade your node to v0.3.0](https://github.com/zeitgeistpm/zeitgeist/releases/tag/v0.3.0).
