### ISSUE TITLE
bug report - Version: 0.2.4-70705a0-x86_64-linux-gnu  0: sp_panic_handler::set::{{closure}}

### ISSUE THREAD

**Issue by kuraassh** [zeitgeistpm/zeitgeist#536]
====================
 Version: 0.2.4-70705a0-x86_64-linux-gnu
    0: sp_panic_handler::set::{{closure}}
    1: std::panicking::rust_panic_with_hook
              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/std/src/panicking.rs:610:17
    2: std::panicking::begin_panic_handler::{{closure}}
              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/std/src/panicking.rs:502:13
    3: std::sys_common::backtrace::__rust_end_short_backtrace
              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/std/src/sys_common/backtrace.rs:139:18
    4: rust_begin_unwind
              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/std/src/panicking.rs:498:5
    5: core::panicking::panic_fmt
              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/core/src/panicking.rs:107:14
    6: core::panicking::panic_display
              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/core/src/panicking.rs:63:5
    7: core::option::expect_failed
              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/core/src/option.rs:1663:5
    8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   11: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   12: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
   13: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
   14: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
   15: tokio::park::thread::CachedParkThread::block_on
   16: tokio::runtime::handle::Handle::block_on
   17: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
   18: tokio::runtime::task::harness::Harness<T,S>::poll
   19: tokio::runtime::blocking::pool::Inner::run
   20: std::sys_common::backtrace::__rust_begin_short_backtrace
   21: core::ops::function::FnOnce::call_once{{vtable.shim}}
   22: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/alloc/src/boxed.rs:1811:9
       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/alloc/src/boxed.rs:1811:9
       std::sys::unix::thread::Thread::new::thread_start
              at rustc/0b6f079e4987ded15c13a15b734e7cfb8176839f/library/std/src/sys/unix/thread.rs:108:17
   23: start_thread
   24: clone
 Thread 'tokio-runtime-worker' panicked at 'A single consensus digest should be added by the runtime when executing the author inherent.', /home/zeitgeist/.cargo/git/checkouts/nimbus-4590fa7f32e5c755/c5ad2f2/nimbus-consensus/src/import_queue.rs:91
 This is a bug. Please report it

**Comment by sea212** [comment]
Thanks for the report. The bug is resolved, please [upgrade your node to v0.3.0](https://github.com/zeitgeistpm/zeitgeist/releases/tag/v0.3.0).
