### ISSUE TITLE
[primitives] `Swaps` trait seems incomplete

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#591]
For example, `pool_join_with_exact_pool_amount` is missing.

**Comment by sea212** [comment]
I think since this trait is not externally used (or atleast not designed to be used externally), we can solve this on demand. If any other pallets needs this, we'll add it to the trait. Low priority seems reasonable to me.

**Comment by maltekliemann** [comment]
No logner relevant.
