### ISSUE TITLE
[simple-disputes] Ramp up the bonds for simple disputes

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#596]

**Comment by sea212** [comment]
We should discuss the implications of that. Chris is currently implementing the global disputes, which are the ultimate judgement. Ramping up the bonds should happen within boundaries that still allow people who do not belong to the top 1% of wealthy people to push the system into the final global dispute if they think the previous dispute is incorrect.

**Comment by maltekliemann** [comment]
We should completely remove simple-disputes.

**Comment by maltekliemann** [comment]
Closing because we're removing simple-disputes.
