### ISSUE TITLE
Benchmark pallets

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/zeitgeist#63]
This is the overarching issue for both #51 and #7 

Benchmarking the extrinsics in Substrate pallets allow us to understand their computation cost at different states in order to find a formula to price them accordingly. For information regarding benchmarking please consult the [Substrate documentation](https://substrate.dev/docs/en/knowledgebase/runtime/benchmarking).

Once we have set up the benchmarking, we can set up a cloud instance that we can run the benchmarks on in order to get a standard pricing.

**Comment by sea212** [comment]
Solved in #65 and #82
