### ISSUE TITLE
`MarketIdsPerReportBlock` and `MarketIdsPerDisputeBlock` are never cleaned up

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#646]
`MarketIdsPerReportBlock` and `MarketIdsPerDisputeBlock` are used as helper hash maps to quickly determine where market state needs to be changed. Once the market is resolved, they are no longer needed, but they are never cleaned up. Doing so should save some space in the long run.

**Comment by Chralt98** [comment]
Isn't [this](https://github.com/zeitgeistpm/zeitgeist/blob/main/zrml/prediction-markets/src/lib.rs#L1316-L1364) fixing the issue?

**Comment by Chralt98** [comment]
I realised, that only the admin extrinsics and the `reject_market` function calls [this](https://github.com/zeitgeistpm/zeitgeist/blob/main/zrml/prediction-markets/src/lib.rs#L1316-L1364). So, could be the solution to call these functions in `on_initialize` after the resolution succeeded?
