### ISSUE TITLE
Audit how many markets can be closed/resolved per block

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#652]
Resources for state transitions are limited. How many should be allowed per block?

**Comment by sea212** [comment]
That's a good point. We might already have the weights for closing or resolving a market, so afaik we should already know how much weight this operations consume. The next step would be to postpone the remaining closing or resolving markets to another block, if the available block weight is already consumed.

**Comment by sea212** [comment]
That's a good point. We might already have the weights for closing or resolving a market, so afaik we should already know how much weight this operations consume. The next step would be to postpone the remaining closing or resolving markets to another block, if the available block weight is already consumed.

**Comment by maltekliemann** [comment]
@Chralt98 I think you're currently working on this.

**Comment by maltekliemann** [comment]
Closing as this isn't a development task. Implementation of a hook scheduler is tracked in the internal tracker.
