### ISSUE TITLE
Ensure that test runs are up to date before merging

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#688]
See https://github.com/zeitgeistpm/zeitgeist/pull/687 for details.

We need to ensure that a PR can only be merged under the following conditions:

- It has been approved by review
- The CI was run against the latest merge commit has passed

**Comment by vivekvpandya** [comment]
I propose to use https://github.com/bors-ng/bors-ng 
I have requested for app access on our zeitgeist repository. @lsaether please approve if you think this everything is fine with that. 
I can create a bors.toml PR to start experiments with bors.

**Comment by vivekvpandya** [comment]
This can be even more automatic https://mergify.com/
Perhaps it does not require trigger like "bors r+"
