### ISSUE TITLE
Add workflow which verifies that the node is producing blocks

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#708]
#683 demonstrates that our testing happens in a vacuum. We should add a test which (at the very least) verifies that the node is capable of producing blocks and responds to RPC.

(This could be done just by adding integration tests.)

**Comment by sea212** [comment]
We have block production tests using Chopsticks, https://github.com/zeitgeistpm/zeitgeist/pull/917, however it would be still very useful to see whether:
1. The client connects to a live network and syncs block (can use rpc to see if best block changes within a couple of minutes)
2. The list of known RPCs works
3. No memory leak exists.

**Comment by maltekliemann** [comment]
@sea212 @Chralt98 *bump*

Should also verify that transactions can be sent.

**Comment by sea212** [comment]
Solved in https://github.com/zeitgeistpm/zeitgeist/pull/1194
