### ISSUE TITLE
Why does `ReportingPeriod` have type `u32` instead of `BlockNumber`?

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#710]

**Comment by sea212** [comment]
Maybe for convenience when coding, not sure about that. It should be `BlockNumber`.

**Comment by vivekvpandya** [comment]
AFAIU BlockNumber is mostly u64, then converting it to Moment requires try_into() as Moment is AtLeastU32 and that does not have From<u64>.
when ReportingPeriod is just a duration so if it is in u32 it can be converted to BlockNumber easily and also (ReportingPeriod * MILLISECS_PER_BLOCK (u32) ) gets converted to Moment.
Also why it should be BlockNumber? if it is just for readability then can we have u32 aliased as BlockDuration and use it for representing such values?

**Comment by maltekliemann** [comment]
Closed as no longer relevant.
