### ISSUE TITLE
[PM] Refactor `process_subsidy_collecting_markets`

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist#714]
**Problem:** As I reviewed the changes of [Vivek's PR here](https://github.com/zeitgeistpm/zeitgeist/pull/713) I noticed, that the function looks ready for a refactoring, because there are many code paths and it's not easy to follow the bracket structure.

https://github.com/zeitgeistpm/zeitgeist/blob/35ecfc20c502a987ef99d4be37cf9b0e7c878b08/zrml/prediction-markets/src/lib.rs#L1839-L2004

**Mitigation approach:** Maybe use multiple functions and/or the `?` operator and results for the return type.

**Comment by maltekliemann** [comment]
Fixed by removing Rikiddo.
