### ISSUE TITLE
What is required to make Moonbeam's staking pallet allow locked tokens to be staked?

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/zeitgeist#715]
I'm opening this issue so we can track the investigation of Moonbeam's staking pallet in order to evaluate the work required to make it work with locked tokens (like the Parity staking pallet does). 

I'll report back and update this issue with some additional information after taking a look at the pallet.

**Comment by lsaether** [comment]
Prior to the v0.25.0 release, Moonbeam's `parachain-staking` pallet used reserves to reserve the currency when bonding. However, after the v0.25.0 release, it now uses locks placed on the currency when bonding which allow the same tokens to be used in other cases where locks are placed such as `Democracy` or when already locked by `Vesting`. Relevant PR: https://github.com/PureStake/moonbeam/pull/1604

In order for us to bring in the changes we need to upgrade to the latest Moonbeam dependencies. @sea212 Can you shed some light on the current pacing of upgrading our dependencies and what's the plan for bringing us up to `parachain-staking` v0.25.0?

**Comment by sea212** [comment]
We won't change the dependencies until after the next release v0.3.5 to ensure stability. We can include it in v0.3.6 though, I don't see anything standing in the way of that.
