### ISSUE TITLE
Verify benchmark logic

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#728]
Verify the benchmark logic for every Zeitgeist pallet currently in use:

- [x] authorized
- [x] prediction-markets
- [x] swaps
- [x] styx

In addition to that, resolve [weight related audit issues](https://github.com/zeitgeistpm/runtime-audit-1/issues/49) (depends on https://github.com/zeitgeistpm/zeitgeist/pull/755).

**Comment by sea212** [comment]
@vivekvpandya Will check the `on_resolution` and admin resolution function once https://github.com/zeitgeistpm/zeitgeist/pull/755 is merged.

**Comment by Chralt98** [comment]
**prediction-markets**
- [ ] on_initialize
- [ ] admin_destroy_market
- [ ] admin_move_market_to_closed
- [ ] admin_move_market_to_resolved
- [ ] approve_market
- [ ] buy_complete_set
- [ ] dispute
- [ ] create_cpmm_market_and_deploy_assets
- [ ] create_market
- [ ] deploy_swap_pool_and_additional_liquidity
- [ ] deploy_swap_pool_for_market
- [ ] redeem_shares
- [ ] reject_market
- [ ] report
- [ ] sell_complete_set

**swaps**
- [ ]  admin_clean_up_pool
- [ ] pool_exit
- [ ] pool_exit_subsidy
- [ ] pool_exit_with_exact_asset_amount
- [ ] pool_exit_with_exact_pool_amount
- [ ] pool_join
- [ ] pool_join_subsidy
- [ ] pool_join_with_exact_asset_amount
- [ ] pool_join_with_exact_pool_amount
- [ ] swap_exact_amount_in
- [ ] swap_exact_amount_out
