### ISSUE TITLE
Add autoformatter or style guide for `.toml` files

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#731]

**Comment by vivekvpandya** [comment]
I have used https://taplo.tamasfe.dev/cli/usage/formatting.html

**Comment by vivekvpandya** [comment]
I propose this simple script https://github.com/zeitgeistpm/zeitgeist/pull/760/files#diff-3a9054a1963ff6cd07b6054d4feecbb4a17b3e4fe87ac71aeb2db3f2524552fb
