### ISSUE TITLE
Make origin tests for specific origins

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#746]
Origin tests in `prediction-markets` and other pallets is very unspecific. We just verify that a single `Sudo` origin can call all restricted calls. However, this leaves room for error: What if `ApproveOrigin` can also call `reject()`, which is supposed to only be called by `RejectOrigin`. If they're all the same in the mock runtime, we can't verify this.

**Comment by sea212** [comment]
Solved in #1265
