### ISSUE TITLE
Track reserved amounts

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#752]
Currently changing the bonds for the prediction market pallet can have ugly consequences, like not unreserving enough if the amounts were lowered or potentially unreserving other reserves. The ZTG price is subject to changes, so those values should be upgradable, ideally by governance. We have to ensure that changing those values does not break the system in any way.

**Comment by maltekliemann** [comment]
I believe that `pallet-identity` has a proper system for tracking bonds, we might be able to copy that.

**Comment by maltekliemann** [comment]
Solved.
