### ISSUE TITLE
Disable building fuzz tests when running `cargo test`

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#769]
See https://github.com/zeitgeistpm/zeitgeist/pull/750#pullrequestreview-1070073145

**Comment by saboonikhil** [comment]
On running `cargo test` in individual pallets (namely orderbook/prediction-markets/rikkido/swaps), I don't think they execute fuzz tests. Could you confirm if that's what you meant? @maltekliemann

**Comment by maltekliemann** [comment]
Yeah, it appears that this is solved already. Thanks for looking into it!
