### ISSUE TITLE
Formatting script can't install tools properly

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#772]
Relevant code: https://github.com/zeitgeistpm/zeitgeist/blob/68cd162577a5b8a1625cb451d924ec06150aaae5/scripts/tests/format.sh#L65-L74

Issues:
1. On Ubuntu, `whereis` returns an empty string if the binary is not found
2. Compiling using the default nightly toolchain results in errors:

<details>
  <summary>
  Expand error log
  </summary>
<pre>
<code>
error[E0658]: `const extern fn` definitions are unstable
    --> /home/sea212/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.132/src/macros.rs:188:17
     |
188  | /                 pub $($constness)* unsafe extern fn $i($($arg: $argty),*
189  | |                 ) -> $ret {
190  | |                     $($body);*
191  | |                 }
     | |_________________^
     |
    ::: /home/sea212/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.132/src/unix/linux_like/mod.rs:1499:1
     |
1499 | / f! {
1500 | |     pub fn CMSG_FIRSTHDR(mhdr: *const msghdr) -> *mut cmsghdr {
1501 | |         if (*mhdr).msg_controllen as usize >= ::mem::size_of::<cmsghdr>() {
1502 | |             (*mhdr).msg_control as *mut cmsghdr
...    |
1545 | |     }
1546 | | }
     | |_- in this macro invocation
     |
     = note: see issue #64926 <https://github.com/rust-lang/rust/issues/64926> for more information
     = help: add `#![feature(const_extern_fn)]` to the crate attributes to enable
     = note: this error originates in the macro `f` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: `const extern fn` definitions are unstable
    --> /home/sea212/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.132/src/macros.rs:203:17
     |
203  | /                 pub $($constness)* extern fn $i($($arg: $argty),*
204  | |                 ) -> $ret {
205  | |                     $($body);*
206  | |                 }
     | |_________________^
     |
    ::: /home/sea212/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.132/src/unix/linux_like/mod.rs:1548:1
     |
1548 | / safe_f! {
1549 | |     pub fn SIGRTMAX() -> ::c_int {
1550 | |         unsafe { __libc_current_sigrtmax() }
1551 | |     }
...    |
1615 | |     }
1616 | | }
     | |_- in this macro invocation
     |
     = note: see issue #64926 <https://github.com/rust-lang/rust/issues/64926> for more information
     = help: add `#![feature(const_extern_fn)]` to the crate attributes to enable
     = note: this error originates in the macro `safe_f` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0658`.
error: could not compile `libc` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `taplo-cli v0.6.10`, intermediate artifacts can be found at `/tmp/cargo-installJw73Ta`

</code>
</pre>
</details>

**Comment by vivekvpandya** [comment]
Yes default nightly version should be based on rust 1.62. See https://github.com/jyao1/rust-spdm/issues/260 (similar issue)
I could not found taplo's version which installs fine with nightly tool chain which is older than 1.62.
