### ISSUE TITLE
When the advisory board rejects a market there is no way to give feedback to the market creator

### ISSUE THREAD

**Issue by Nathanpmyoung** [zeitgeistpm/zeitgeist#795]
This is frustrating to market creators

**Comment by maltekliemann** [comment]
This is somewhat related to #742.

On the chain side, we can fix this by adding a short message in an event, similar to how `System::remark()` works. But to facilitate a proper back-and-forth between advisor and user, we need a comment function on the frontend.

**Comment by vivekvpandya** [comment]
do we want feature from front-end? or I can add RejectReason in reject_market extrinsic and then return it in event.

**Comment by maltekliemann** [comment]
I like the `EditReason` you built into #834. That allows us to have a track record on the blockchain. But I think there should also be a front-end solution.

**Comment by maltekliemann** [comment]
Opened an issue about this: zeitgeistpm/ui#346.
