### ISSUE TITLE
[benchmarking-cli] Benchmark database (db) read and write access times on the current chain state

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist#798]
How do we currently benchmark the read and write times for storage items?

Is there a default setting anywhere?

According to this: https://github.com/paritytech/substrate/blob/master/utils/frame/benchmarking-cli/src/storage/README.md

**Comment by sea212** [comment]
The client is already capable to do this, but this feature was not utilized until now. The system uses the quite conservative default values.

**Comment by maltekliemann** [comment]
Closing as resolved.
