### ISSUE TITLE
The market can be easily arbitraged

### ISSUE THREAD

**Issue by Nathanpmyoung** [zeitgeistpm/zeitgeist#799]
eg. https://insights.hotjar.com/r?site=3155607&recording=15458737586&workspace_id=2782177

**Comment by Nathanpmyoung** [comment]
Do we know what % of use is arbitraging currently?

**Comment by maltekliemann** [comment]
Yeah, good to have an issue for this. We're already planning a new AMM design which will mitigate this problem.

**Comment by Nathanpmyoung** [comment]
Does this board have a system for denoting the size of issues?

Yours,

Nathan Young

*M* 07891 020271
*W* nathanpmyoung.com
*T  ***@***.*** <https://twitter.com/nathanpmyoung>

Personal newsletter <https://tinyletter.com/nathanpmyoung>

If I can put you in touch with someone, please ask.

Sent via Superhuman iOS ***@***.***>

**Comment by maltekliemann** [comment]
By size you mean "How much work is it going to take to fix it?" or "How bad is it?". We use priorities for the latter. I'd like to start adding the size in the sense of workload very soon, as well.

This particular issue would be quite large.

**Comment by sea212** [comment]
> I'd like to start adding the size in the sense of workload very soon, as well.

I agree, this would be helpful. Let's talk about it in the next meeting.
