### ISSUE TITLE
Use serde for custom structs/enums

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#80]
Currently serde is included but not used in the pallets. In a std-environment, use serde to serialize and deserialize the data structures.

**Comment by c410-f3r** [comment]
@sea212 `serde` was used before because some macros were generating code with it. For example:
```rust
macro_rules! foo {
  () => {
    #[serde::Serialize]
    struct Foo;
  }
}
```

With #164, it seems that this constraint is not necessary any-more and most `serde` dependencies were removed. Can I close this issue?
