### ISSUE TITLE
Add rpc call to fetch historical asset prices for a pool over a range of blocks.

### ISSUE THREAD

**Issue by yornaath** [zeitgeistpm/zeitgeist#804]
The current SDK only has support for listing price history for assets in a pool when connecting to the indexer, and it is my aim to be able to provide some capacity of this functionality using node rpc alone in the sdk v2.

The currently implemented rpc method `swaps.get_spot_prices` satisfies the requirement for getting the prices of one asset over a range of blocks, but needs to be called `N` amount of times for the number of assets in the pool.

I am suggesting somethings like the following rpc interface; that would list all asset prices pr _non ztg_ asset in the pool for a range of blocks. _My types might be wrong so think of it as pseudocode if they are_ ^^

```rust
fn get_asset_spot_prices_for_pool(
  &self,
  pool_id: PoolId,
  blocks: Vec<BlockNumber>,
) -> Result<BTreeMap<Asset, Vec<SerdeWrapper<Balance>>>>;
```

_This would make it less io intensive to fetch all relevant asset price histories when viewing a market through rpc alone and you want some price history graph or the like; as you would have to make only one call._

**Also relevant to ensure correct typing when interacting with the rpc calls in the sdk is this issue:** #803

**Comment by vivekvpandya** [comment]
fn get_asset_spot_prices_for_pool(
  &self,
  pool_id: PoolId,
  blocks: Vec<BlockNumber>,
) -> Result<BTreeMap<Asset, Vec<SerdeWrapper<Balance>>>>;

I think here we don't need Vec of Balance in map, map of asset_Id to balance is sufficient.
For all assets except base_asset, price will be returned with in as asset and out as base_asset.

**Comment by vivekvpandya** [comment]
Based on https://users.rust-lang.org/t/serde-hashmap-serialization-key-error/49776/7 and https://github.com/serde-rs/serde/issues/1428 I think Asset can be be key for a map in JSON as per its current serialization.


Best we can do is either Map<block , (Asset, Balance) or Vec<(block, asset, balance)>

**Comment by vivekvpandya** [comment]
I have updated PR to use Map<Block, (Asset, Balance) > as return type.
https://github.com/zeitgeistpm/zeitgeist/pull/971
Attached JS which  used to test.
[spot_price.txt](https://github.com/zeitgeistpm/zeitgeist/files/10782447/spot_price.txt)
