### ISSUE TITLE
[PM] Push overweight of market status manager to next block

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist#817]
Related to [this](https://github.com/zeitgeistpm/zeitgeist/blob/30b7191666809c5f40293b0e815c9336d3a9ec91/zrml/prediction-markets/src/lib.rs#L2199-L2209).

> I would like ask, you, @maltekliemann and @sea212, if we like to benchmark the market_status_manager in the case, that the last time frame is far behind the current time frame [here](https://github.com/zeitgeistpm/zeitgeist/blob/30b7191666809c5f40293b0e815c9336d3a9ec91/zrml/prediction-markets/src/lib.rs#L2199-L2209) ? I think as I benchmarked it currently, it's sufficient enough, because of this:
> 
> ```rust
> market_ids_per_time_frame_len = market_ids_per_time_frame_len
>                     .saturating_add(market_ids_per_time_frame.len() as u32);
> ```
> 
> So if we have more than 1 iteration in the parent for-loop, then we simply put a higher benchmark component inside the weight function.
> 
> If you agree, then I would delete the comments, as you suggested. Since Substrate doesn't really like to benchmark quadratic weights, I would also strongly suggest to avoid the use of two nested for-loops.

Sorry, I didn't get to answering this yet. I think we need to take a look at what the `market_status_manager` does to understand how to benchmark it. First of all, I'd say the approach that you took is a good choice right now. A slightly different approach would be to benchmark the weight of the inner loop depending on the size of the iterator and then adding all those weights up. Not sure how feasible this is, though.

Long-term, we should think about the following: The market status manager is called in `on_initialize` to change the status of markets, so it opens or closes these markets. These are critical operations, unlike, say, deleting assets, these _shouldn't_ be delayed. On the other hand, if the chain skips too many blocks, there's no cap to how many markets we need to open/close/etc. on one block, so the water-tight, bullet-proof, perfect solution would be to reserve a certain amount of the weight for this type of operation, estimate how much work can be done in that time and shift unhandled markets to the next block's `on_initialize`.

_Originally posted by @maltekliemann in https://github.com/zeitgeistpm/zeitgeist/pull/807#discussion_r984969769_

Another useful comment about this [here](https://github.com/zeitgeistpm/zeitgeist/pull/807#discussion_r987833130).

From @maltekliemann:

> Of course, the worst case for `market_status_manager` is not `CacheSize::get()`; it's a very large difference between `current_time_frame` and `last_time_frame`, and each time frame holds `CacheSize::get()`. The larger the gap between the time frames, the larger the weight.

> I don't think we should do this right now, but can you open an issue that we need to basically delay status changes until the next block if there are too many markets to handle? I would do it like this:

> - Set a maximum weight for status changes `m`
> - Benchmark the weight of a single status change `w`; if we need to handle more markets than `m / w` markets, we need to delay the status change until the next block

>This basically boils down to having a priority system, where the weight `m` needs to be distributed between a couple of tasks (status changes, garbage collecting) and opening/closing is more important than resolving, which in turn is more important than garbage collection.

> This shouldn't be difficult to implement, we just need to find the time to do it.

**Comment by maltekliemann** [comment]
Implementing garbage collection is tracked internally.
