### ISSUE TITLE
[pallet_collective] Benchmark failure for `propose_proposed`

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist#822]
Running following command:

```bash
./target/release/zeitgeist benchmark pallet --chain dev --execution=wasm --wasm-execution=compiled --heap-pages=4096 --pallet "pallet_collective" --extrinsic "propose_proposed" --steps 1 --repeat 0
```

I get `Error: Input("DuplicateProposal")`. It seems like a configuration value is not set correctly for `pallet_collective`.

I investigate some time for it and also to check inside the CI, that all release benchmarks work correctly.

- [x] Correct pallet_collective config parameters

So it fails [here](https://github.com/paritytech/substrate/blob/174735ea1bb5fc4513519c45181d8df63d86f613/frame/collective/src/lib.rs#L520-L523) (for v0.9.19). And [here](https://github.com/paritytech/substrate/blob/174735ea1bb5fc4513519c45181d8df63d86f613/frame/collective/src/benchmarking.rs#L186-L201) is the benchmark. We only add a benchmark for the `AdvisoryCommittee` [here](https://github.com/zeitgeistpm/zeitgeist/blob/cadca835826737725f24b798612a27a9f2b095b9/runtime/common/src/lib.rs#L1116). The `MaxProposals` for the AdvisoryCommittee are set to `300` on [battery-station](https://github.com/zeitgeistpm/zeitgeist/blob/cadca835826737725f24b798612a27a9f2b095b9/runtime/battery-station/src/parameters.rs#L61) and [main-net](https://github.com/zeitgeistpm/zeitgeist/blob/cadca835826737725f24b798612a27a9f2b095b9/runtime/zeitgeist/src/parameters.rs#L61).

Since the creation of proposals produce [hashes with `u8`](https://github.com/paritytech/substrate/blob/174735ea1bb5fc4513519c45181d8df63d86f613/frame/collective/src/benchmarking.rs#L199), the number of `300` for `MaxProposals` is too high, because `u8` will only produce unique hashes for `255` proposals. 

Created an issue for that [here](https://github.com/paritytech/substrate/issues/12433).
 
- [x] Update the CI to quick check benchmarks

I would suggest the following command:

```bash
./target/release/zeitgeist benchmark pallet --chain dev --execution=native --wasm-execution=compiled --heap-pages=4096 --pallet "*" --extrinsic "*" --steps 1 --repeat 0 --detailed-log-output
```

**Comment by sea212** [comment]
Can this be closed @Chralt98 ?

**Comment by sea212** [comment]
nvm, https://github.com/zeitgeistpm/zeitgeist/pull/825 is still open.
