### ISSUE TITLE
Remove remnants of on-chain arbitrage

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#837]
When on-chain arbitrage is removed in favor of a fixed market maker, we need to remove the improvised solution for accessing the prize pool from `swaps`.

**Comment by Chralt98** [comment]
I think it's not in swaps anymore now, it's in market commons, but still, it shouldn't belong to market-commons (because the prediction market pallet id is used to calculate the account id of the prize pool)
