### ISSUE TITLE
Rpc calls getSpotPrice(s) take swap fees into consideration by default.

### ISSUE THREAD

**Issue by yornaath** [zeitgeistpm/zeitgeist#840]
The rpc calls to fetch spot prices take fees into consideration when calculating prices, while the indexer does not. This leads to some inconsistency in results when implementing a transparent call in the new sdk that can work with both indexer or rpc.

Could we add a optional flag to the calls to include fees or not? Making it an option so it can be omitted defeault being not including fees when calculating prices?
```with_fees: Option<bool>```

**Comment by vivekvpandya** [comment]
I feel using Option<bool> is bit confusing because then for both value None and Some(false) it means not include fees.
Better use bool at rust level and perhaps at TS sdk level we can use bool with default value false.
