### ISSUE TITLE
ZIP-0 Crowdfund disputes to build a dispute party

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist#854]
Disputes should be expensive, but also be made by multiple small fishes.

https://github.com/zeitgeistpm/zeitgeist-improvement-proposals/blob/main/zip-0-dispute-overhaul/dispute_overhaul.md#allow-crowdfunding-of-disputes

This could be helpful:

https://docs.substrate.io/reference/how-to-guides/pallet-design/configure-crowdfunding/

The crowdfunding functionality should be in its own pallet.

**Comment by maltekliemann** [comment]
Outdated for now. We can reopen if we ever pick this up.

**Comment by maltekliemann** [comment]
Might also be a good application of smart contracts.
