### ISSUE TITLE
unpin tracing-core from version 0.1.26

### ISSUE THREAD

**Issue by vivekvpandya** [zeitgeistpm/zeitgeist#865]
Due to following issue for polkadot-v0.9.26 we have to use tracing-core at version 0.1.26.
https://github.com/paritytech/substrate/issues/11691

In future version of polkadot we can remove this requirement.

**Comment by saboonikhil** [comment]
Nursed at https://github.com/zeitgeistpm/zeitgeist/pull/887/commits/0dae75f08f5ac44e2b70126f6cf3b038fcfbad75? @maltekliemann

**Comment by maltekliemann** [comment]
Yeah, this is solved already, thanks!
