### ISSUE TITLE
ZIP-0 Reserve an `OutsiderBond` for `report`, when the oracle fails to report

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist#868]
This is related to https://github.com/zeitgeistpm/zeitgeist/issues/698 . Don't forget to close #698, when this is resolved.

Slash the deposit, when the `resolved_outcome` is not the reported outcome in `on_resolution`.

Unreserve the `OutsiderBond` when the market resolves and [repatriate](https://paritytech.github.io/substrate/master/frame_support/traits/trait.ReservableCurrency.html#tymethod.repatriate_reserved) the `OracleBond` to the outsider.

Keep in mind that the `OutsiderBond` should be transferred to the right disputors like [here](https://github.com/zeitgeistpm/zeitgeist/blob/f8f5c79c7c49c9011ab00ffa670d40dab48d44b7/zrml/prediction-markets/src/lib.rs#L2341).

**Comment by maltekliemann** [comment]
The report should contain the info how much was reserved so we don't run into trouble in the future when changing bond values.
