### ISSUE TITLE
Nodes out of sync

### ISSUE THREAD

**Issue by COLUD4** [zeitgeistpm/zeitgeist#876]
Node not connecting to peer after 0.3.6 upgrade

**Comment by erik78se** [comment]
Not sure from the above if this is the same issue, but I'm stuck with the Zeitgeist Parachain not syncing:

```
Nov 13 20:02:23 juju-105421-4 polkadot[12690]: 2022-11-13 20:02:23 [🌔 Zeitgeist Parachain] 💤 Idle (0 peers), best: #0 (0x1bf2…e060), finalized #0 (0x1bf2…e060), ⬇ 0 ⬆ 0
Nov 13 20:02:23 juju-105421-4 polkadot[12690]: 2022-11-13 20:02:23 [Relaychain] ⚙️  Syncing 598.2 bps, target=#15314321 (10 peers), best: #1159599 (0xfe6d…c7ee), finalized #1159168 (0xa7a7…59b4), ⬇ 337.6kiB/s ⬆ 31.3kiB/s

```

polkadot --version
polkadot 0.3.6-8c6395fc152

I've got the same bahaviour on an earlier release: 0.3.5

I've got the same behaviour on a completely fresh node with no database. Getting 0 peers for the Parachain.

**Comment by sea212** [comment]
The relaychain contained a rogue block that had some data in it that lead to a crashloop on Zeitgeist nodes. To workaround the issue, you have to resync the Kusama chain within the Zeitgeist base path. Using a snapshot should also be possible. Another variant (the quickest and dirtiest) is to lauch the polkadot client v0.9.30 using the base path pointing to the "kusama" folder within the Zeitgeist basepath and using `--chain kusama`. The chain will sync past the problematic block and then Zeitgeist will continue to sync blocks. When going with that approach, ensure that the Kusama and Zeitgeist instance are not running simultaneously.

The next release will contain a fix for those kind of crashes.

**Comment by erik78se** [comment]
For some reason, just an hour ago, the block production started again. 

Nov 14 19:37:14 juju-105421-0 polkadot[295614]: 2022-11-14 19:37:14 [🌔 Zeitgeist Parachain] 💤 Idle (10 peers), best: #1694620 (0x6fc1…5073), finalized #1694617 (0x8d79…7979), ⬇ 0.9kiB/s ⬆ 0.9kiB/s

No clue as what has "unstuck" the chain.
