### ISSUE TITLE
Lifecycle of pool account on `predictionMarkets.adminDestroyMarket`

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/zeitgeist#882]
During my analysis, I found that `system.KilledAccount` is not generated for the pool account on execution of `predictionMarkets.adminDestroyMarket`. However balances are slashed. Is that an expected result?

I am planning to wipe out balances of the pool account post processing of `swaps.PoolDestroyed` on subsquid.

Example: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/2228083

**Comment by Chralt98** [comment]
I can see `system.KilledAccount` in your example. This is not the pool account (dE1VdxVn8xy7HFH9dLfdbA4GthTxng6A6b3NU6bWnxLSYWmGv)?

Yeah, the asset balances are slashed from the pool account [here](https://github.com/zeitgeistpm/zeitgeist/blob/6fcdae899ed74fe71ede533ce9741750bee63935/zrml/swaps/src/lib.rs#L1835-L1839) for `adminDestroyMarket`.

You are right, indeed, when every balance is [below the existential deposit, then the account is killed](https://github.com/paritytech/substrate/blob/61b9a4d1a8a9bf39c1d89a8dd02f82785c10860c/frame/balances/src/tests_local.rs#L156-L191). If this event was not emitted, then the account wasn't fully empty.

**Comment by saboonikhil** [comment]
This should be the pool account `dE1VdxVn8xy7HFNWfF26oju65FMjRuppmbrdMsVRqyeVbBscx` for poolId `143`

**Comment by Chralt98** [comment]
<img width="1722" alt="Bildschirmfoto 2022-11-24 um 08 14 54" src="https://user-images.githubusercontent.com/33418719/203717851-85c89fef-f25c-4d16-9798-1cabd36e05ae.png">

In your example, when I query at the specified block hash for the `system` pallet I get a provider number of `2`. To get the event `system.KilledAccount` we would need `0` providers.

**Comment by Chralt98** [comment]
One additional information is, that we on the node team discussed the usage of `adminDestroyMarket` in the future and came to the conclusion, that we'd like to remove that extrinsic completely and just be in favour of removing the market's visibility on the app.

**Comment by Chralt98** [comment]
> I am planning to wipe out balances of the pool account post processing of swaps.PoolDestroyed on subsquid.

After the pool is destroyed, you could query all assets (including base asset) of the pool and check if those are zero. Sure, it's easier to listen to an event like `system.KilledAccount`, but since other pallets protect the reap of the account, you just need to listen for the event `swaps.PoolDestroyed` to assume, that we slashed all assets.

**Comment by saboonikhil** [comment]
> > I am planning to wipe out balances of the pool account post processing of swaps.PoolDestroyed on subsquid.
> 
> After the pool is destroyed, you could query all assets (including base asset) of the pool and check if those are zero. Sure, it's easier to listen to an event like `system.KilledAccount`, but since other pallets protect the reap of the account, you just need to listen for the event `swaps.PoolDestroyed` to assume, that we slashed all assets.

Yep, that should help! (Cheers to the morning 🥤)

**Comment by Chralt98** [comment]
A short addendum: The reason, that providers is not zero, is that [`orml_tokens` is configured by us](https://github.com/open-web3-stack/open-runtime-module-library/blob/10cdcf1312f2cfb9ed957661c14058c7834193b8/tokens/src/lib.rs#L741) so, that the Existential Deposit is zero for any non-native asset [here](https://github.com/zeitgeistpm/zeitgeist/blob/31a123a84eb0aaf216da9484d5c529517cda6004/runtime/zeitgeist/src/parameters.rs#L375).
