### ISSUE TITLE
Fix client connection issue introduced after upgrade to polkadot-v0.9.26.

### ISSUE THREAD

**Issue by vivekvpandya** [zeitgeistpm/zeitgeist#883]

**Comment by sea212** [comment]
Also fixes https://github.com/zeitgeistpm/zeitgeist/issues/919 . In fact https://github.com/zeitgeistpm/zeitgeist/issues/919 is already fixed, but publishing a new client depends on this issue.

**Comment by melekes** [comment]
Refs https://github.com/paritytech/substrate/issues/12704

Can we have more details here? Like how to replicate? What exactly are the issues you're experiencing? Thank you 🙏

**Comment by vivekvpandya** [comment]
> Refs [paritytech/substrate#12704](https://github.com/paritytech/substrate/issues/12704)
> 
> Can we have more details here? Like how to replicate? What exactly are the issues you're experiencing? Thank you pray

Zeitgiest's release v0.3.6 connects and syncs with para-chain node with in seconds however after upgrade to polkadot-v0.9.26 (that is zeitgiest's main branch) it does not connect and sync for parachain.

**Comment by sea212** [comment]
Connection issue seems to be resolved since Zeitgeist v0.3.9
