### ISSUE TITLE
Let market creators set the size of the oracle bond

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#889]
Of course, there should be a required minimum. The size of the bond characterizes the oracle's commitment to the market. This solves the following problem: You create a market which would attract 100,000 ZTG liquidity, but the oracle bond is a couple of hundred ZTG. Relative to the size of the market, this does not make the market sufficiently resistant to bribery and other attacks. The higher the oracle's bond, the higher the confidence of the traders that the oracle will report correctly.

**Comment by Chralt98** [comment]
We could also make a bidding system out of this report scheme. Just let everyone bid their report outcome and the highest bid in a certain time is the submitted report. Then we don't even need a dynamic or constant bond, we just let the market decide.

**Comment by maltekliemann** [comment]
Needs clarification and is part of the planned protocol simplification.
