### ISSUE TITLE
[XCM] Ensure existential deposits for external assets other than ZTG

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/zeitgeist#907]
We need to implement existential deposit logic https://github.com/zeitgeistpm/zeitgeist/blob/f8f5c79c7c49c9011ab00ffa670d40dab48d44b7/runtime/battery-station/src/parameters.rs#L372

cc @Chralt98

**Comment by sea212** [comment]
Handled in https://github.com/zeitgeistpm/zeitgeist/issues/726#issuecomment-1307373173
