### ISSUE TITLE
Add a `close` extrinsic to close a market early

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#909]
The point of having this is to equip the market creator with a simple option to end a market and the liquidity in case of information shock. The may or may not want another button for opening the market again.

**Comment by Chralt98** [comment]
What is an information shock for you? Why should the market be closed in this case? Does close markets early feature already solve your problem or was your issue about reopening it again after the closure?

**Comment by maltekliemann** [comment]
I think _information shock_ is the wrong term here. This is about trivialized markets where the outcome has publicly known, so this is fixed by early close.
