### ISSUE TITLE
Test runtime upgrades with Chopstick

### ISSUE THREAD

**Issue by vivekvpandya** [zeitgeistpm/zeitgeist#915]

**Comment by sea212** [comment]
Chopsticks introduction post: https://forum.polkadot.network/t/chopsticks-substrate-testing-client/878
Github repository: https://github.com/AcalaNetwork/chopsticks
Presentation (with code examples): https://www.youtube.com/watch?v=IJqbO45DVIA

We need a script that uses Chopstick to automate runtime upgrade tests for our live networks. Essentially it should clone the latest state and execute a runtime upgrade to test if block production continues. It will be used additionally to `try-runtime`.

**Comment by Chralt98** [comment]
Chopsticks will be indirectly integrated using Moonwall here https://github.com/zeitgeistpm/zeitgeist/issues/1186

**Comment by sea212** [comment]
Solved in https://github.com/zeitgeistpm/zeitgeist/pull/1194
