### ISSUE TITLE
ZIP-0 Attach comment to dispute instead of an outcome

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#916]
@Chralt98 Not sure how compatible this is with your plans, but I keep thinking about clone-resistance, and I think both authorized and the decentralized court don't really need the suggestion. Instead, we could let someone attach a comment with a max length explaining why they think the dispute is justified. I mention in ZIP-0 that I think the suggestion should be removed. Using a comment seems to be the correct replacement for the suggestion.

Which also raises another question: When should the dispute bond be slashed? Currently, it's if the market resolves to something other than the disputant's suggestion. Again, this isn't clone-resistant.

- [ ] remove outcome suggestion from the `dispute` extrinsic

**Comment by Chralt98** [comment]
I am also in favour of not attaching an outcome at all to the `dispute` extrinsic inside prediction-markets. 

Here is another thing: We shouldn't reserve a bond at all when calling `dispute`. It should just allow each MDM to take over (change to `MarketStatus::Disputed`).

A bond is useful for `simple-disputes`. Show ZIP-0 has got the suggestion to move many things from prediction-markets to simple-disputes.

**Comment by maltekliemann** [comment]
Seems solved. Adding evidence is part of another issue already.
