### ISSUE TITLE
Excessive node memory usage

### ISSUE THREAD

**Issue by COLUD4** [zeitgeistpm/zeitgeist#919]
The node's memory usage is too high, sometimes exceeding 50G, which then leads to oom, is there any way to optimize the node's memory usage?

**Comment by maltekliemann** [comment]
This is most likely related to a memory leak that the client v0.3.6 suffers from. Until we've resolved the issue you should continue using client v0.3.5 insetad.

**Comment by sea212** [comment]
Resolved in v0.3.8
