### ISSUE TITLE
MarketResolved event should also have block_number at which it was resolved.

### ISSUE THREAD

**Issue by vivekvpandya** [zeitgeistpm/zeitgeist#939]
By having this change, it will also get cached in SubSquid.

**Comment by sea212** [comment]
@saboonikhil Does Subsquid not associate block numbers to events automatically?

**Comment by saboonikhil** [comment]
> @saboonikhil Does Subsquid not associate block numbers to events automatically?

The block containing the event is recorded on the history of the respective market.

<img width="355" alt="Screenshot 2023-01-17 at 7 34 06 PM" src="https://user-images.githubusercontent.com/36529278/212919116-58c28847-0939-4634-acf8-8a4a8690a8ec.png">

**Comment by vivekvpandya** [comment]
We can close this as once market is resolved there is not much use of having this information on-chain. And subsquid is already capturing this.
