### ISSUE TITLE
[prediction-markets] Auto-deploy a pool when approving a market

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#949]
Advised markets should give use the option to auto-deploy a pool when the market is approved. One implementation would be to allow users to actually create a pool for a `Proposed` market but to leave the pool inactive until the market is approved.

This solves the following problem: Other users can deploy a pool on a newly approved market, set poorly thought-out odds for the pool and then withdraw as much liquidity as possible, just to grief the original market creator. Another solution would be to set permissions which allow only the market creator to deploy a pool, but I think quite often the market creator will wish to auto-create a pool.

**Comment by maltekliemann** [comment]
We may also want to make people deposit a bond when they deploy a pool.

**Comment by sea212** [comment]
Depends on AMM 2.0

**Comment by maltekliemann** [comment]
Outdated due to upcoming protocol simplifications.
