### ISSUE TITLE
How to delay the oracle report time limit if the market ends too soon?

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist#956]
Related to this https://github.com/zeitgeistpm/zeitgeist/pull/903#discussion_r1082536580

> I see one scenario which bothers me. What if the market was misconfigured and the market ends too soon so that there's no outcome to report. The oracle solves this problem by not reporting (seems like the best course of action available to the oracle). Then some outsider ignorantly reports something, a dispute ensues and in the end, both are slashed. Seems unfair to the oracle, which always acted with good intent.

> What I'm getting at is that this setup is incentivizing the oracle in this situation to report a random outcome in the hope of guessing the correct outcome so that it doesn't get slashed. Even worse, if the oracle is smart, it will probably "guess" the outcome with the highest prediction.

> One thing to keep in mind with this is that the oracle should propose an outcome. Otherwise I could as market creator just set the oracle duration to the minimum and just wait with my oracle outcome submit until the oracle duration is over to eventually get my bond back. Market creators are then incentivised to set the periods incorrectly so that it's justified that the market ended too soon.

**Comment by maltekliemann** [comment]
This problem is quite complex. The first step is to move the early resolution to court. Should be split in multiple issues, so I'm closing for now until we've defined the scope. (Tracked by our internal tracker.)
