### ISSUE TITLE
Use identical fractional decimal places for any token

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#969]
Foreign tokens that can be received via cross-consensus reserve transfers have a different number of decimal places. This renders a problem when costs and rewards in markets and pools are calculated. I am aware of two ways to handle this:
1. Update core math to be able to handle different decimal places
2. Enforce the same number of decimal places for any token

Using the first approach introduces a couple of problems:
1. The core logic of arithmetic has to be changed. This is a very dangerous operation and requires a huge amount of resources to ensure that the changes are sound
2. The front-end applications have to deal with many different representations

Using the second approach seems to be an easy and straightforward way to eliminate the problems that arise with solution 1. When foreign assets enter the system, they are either trimmed or padded to the correct number of fractional places. In both cases the situation that more foreign tokens exist than are available in the reserve cannot occur since no new tokens are minted other than through arriving reserve asset transfers.

**Comment by vivekvpandya** [comment]
So only way to handle this issue in Rust is to either implement custom fork of  https://github.com/open-web3-stack/open-runtime-module-library/blob/master/xcm-support/src/currency_adapter.rs#L155  and do the required conversion.
How ever I could not find such example in any other project. 
Most polkadot projects are relying on JS to convert and provide appropriate values. 
I.e if ZTG uses 12 decimals for precision any project want to send their tokens to Zeitgeist they must send raw value which already converted to 12 decimals, and similarly when Zeitgeist wants to send tokens back to other chain , it must convert value back to precision of receiving chain. And this all can handle in JS.

And there is also effort to aggregate information about XCM assets https://github.com/colorfulnotion/xcm-global-registry
 https://github.com/colorfulnotion/xcm-global-registry/blob/main/xcmRegistry/polkadot_xcmRegistry.json
https://forum.polkadot.network/t/xcm-global-asset-registry-gar-call-for-contributors/1470/5
