### ISSUE TITLE
Properly configure Proxies

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#970]
Currently the Proxies offer a very limited permission control. Create a fine-granular whitelist of Proxy calls.

**Comment by maltekliemann** [comment]
Different types of proxies we may want to consider:

-   Trading/LPing packet: Buying/selling tokens, roviding/removing liquidity, buying/selling full sets, redeeming outcome tokens
-   Reporting/Disputing
-   Market Creation
-   Small cap extrinsics
-   Trading
-   Argument validation (trades less than x amount of DOT)
