### ISSUE TITLE
ZIP-2 Integrate crowdfund pallet into court

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist#978]
Currently the plan is that Forecasting Technologies provides the voting outcomes for the court mechanism. We want to fund outcomes with crowdfunding to have a decentralized way of it.

https://github.com/zeitgeistpm/zeitgeist/blob/51b2e04ceb38651fbb368a782ddc19b7c7461414/zrml/court/src/lib.rs

The above had integrations of the `Crowdfund` functionality. We decided to remove them, because of development speed.

**Comment by maltekliemann** [comment]
Closing as this is too far out of reach right now. Crowdfunding will probably be done via smart contract anyways.
